### ISSUE TITLE
[Bug] Error in Mod Menu

### ISSUE THREAD

**Issue by EvanHsieh0415** [isXander/Zoomify#126]
```java
[Render thread/ERROR]: Error from mod 'zoomify'
java.lang.IncompatibleClassChangeError: Found interface dev.isxander.yacl.api.YetAnotherConfigLib$Builder, but class was expected
	at dev.isxander.settxi.gui.yacl.SettxiYACLGuiKt.yetAnotherConfigLib(SettxiYACLGui.kt:24) ~[transformed-mod-settxi-gui-yacl.i0:0/:?]
	at dev.isxander.zoomify.config.ZoomifySettings.gui(ZoomifySettings.kt:374) ~[transformed-mod-zoomify.i0:0/:?]
	at dev.isxander.zoomify.integrations.ModMenuIntegration.getModConfigScreenFactory$lambda$0(ModMenuIntegration.kt:9) ~[transformed-mod-zoomify.i0:0/:?]
	at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:57) ~[transformed-mod-modmenu.i0:0/:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25426(ModsScreen.java:113) ~[transformed-mod-modmenu.i0:0/:?]
	at net.minecraft.class_437.method_41843(class_437.java:389) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_437.method_25423(class_437.java:380) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1507(class_310.java:1035) ~[transformed-mod-minecraft.i0:0/:?]
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:14) ~[transformed-mod-modmenu.i0:0/:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:43) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_339.method_25402(class_339.java:120) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_437.method_25412(class_437.java:489) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[transformed-mod-minecraft.i0:0/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) [lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) [lwjgl-glfw-3.3.1.jar:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197) [transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:315) [transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1205) [transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [transformed-mod-minecraft.i0:0/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527) [quilt-loader-0.18.3.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) [quilt-loader-0.18.3.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) [quilt-loader-0.18.3.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
```

**Comment by isXander** [comment]
downgrade to yacl 1.x
