### ISSUE TITLE
Trying to edit Zoomify's options crashes Minecraft.

### ISSUE THREAD

**Issue by MidoriMushrooms** [isXander/Zoomify#157]
There is no config button in the mod menu for some reason, so I attempted to use the /zoomify command and was met with this crash report:

```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2023-06-11 23:17:02
Description: Unexpected error

java.lang.IncompatibleClassChangeError: Found interface dev.isxander.yacl.api.YetAnotherConfigLib$Builder, but class was expected
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28)
	at dev.isxander.settxi.gui.yacl.SettxiYACLGuiKt.yetAnotherConfigLib(SettxiYACLGui.kt:24)
	at dev.isxander.zoomify.config.ZoomifySettings.gui(ZoomifySettings.kt:374)
	at dev.isxander.zoomify.Zoomify.tick(Zoomify.kt:130)
	at org.quiltmc.qsl.lifecycle.api.client.event.ClientTickEvents.lambda$static$2(ClientTickEvents.java:54)
	at net.minecraft.client.MinecraftClient.handler$ffn001$quilt_lifecycle_events$endTick(MinecraftClient:20005)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1907)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1135)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

Here is a pastebin with the full crash report, which was too long for github: https://pastebin.com/4Sfy7iKT

Edit:
Minecraft version: 1.19.2
Modloader: Quilt Loader 0.18.10

**Comment by Xeracle** [comment]
I'm having this issue as well. No ideas on how to fix it.

**Comment by Obsidianninja11** [comment]
I'm having this too

**Comment by FinalKirb** [comment]
Same problem here as well, impossible to reconfigure it. Quite inconvenient because the out-of-the-box zoom is way too slow for me

**Comment by isXander** [comment]
You are on 1.19.2. Which is unsupported. Please use YACL 1.x rather than 2.x for this to work.

**Comment by MidoriMushrooms** [comment]
2.8.0 is listed as supported for 1.19.2 on the Curseforge page though?
