### ISSUE TITLE
Zoomify on Curseforge will not work due to a required depency not existing.

### ISSUE THREAD

**Issue by coldReactive** [isXander/Zoomify#166]
`- Mod 'Zoomify' (zoomify) 2.10.0 requires any version of yet_another_config_lib_v3, which is missing!`

yet_another_config_lib_v3 doesn't exist for curseforge.

**Comment by isXander** [comment]
https://curseforge.com/minecraft/mc-mods/yacl

**Comment by Iwaku-Real** [comment]
I'm getting that error with the latest version of `yet_another_config_lib_v3` (`yet-another-config-lib-forge-3.1.0+1.20.jar`):
`Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install yet_another_config_lib_v3, any version.
Unmet dependency listing:
	 - Mod 'Zoomify' (zoomify) 2.10.0 requires any version of yet_another_config_lib_v3, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)`
