### ISSUE TITLE
[1.19.2] Crash on /zoomify command

### ISSUE THREAD

**Issue by Zarvera** [isXander/Zoomify#182]
I'm not seeing any settings button in Mod Menu for Zoomify. More importantly, /zoomify command crashes the instance with following output:
Description: Unexpected error

java.lang.IncompatibleClassChangeError: Found interface dev.isxander.yacl.api.YetAnotherConfigLib$Builder, but class was expected
	at dev.isxander.settxi.gui.yacl.SettxiYACLGuiKt.yetAnotherConfigLib(SettxiYACLGui.kt:24)
	at dev.isxander.zoomify.config.ZoomifySettings.gui(ZoomifySettings.kt:374)
	at dev.isxander.zoomify.Zoomify.tick(Zoomify.kt:130)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$deg000$fabric-lifecycle-events-v1$onEndTick(class_310.java:12980)
	at net.minecraft.class_310.method_1574(class_310.java:1907)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.isxander.settxi.gui.yacl.SettxiYACLGuiKt.yetAnotherConfigLib(SettxiYACLGui.kt:24)
	at dev.isxander.zoomify.config.ZoomifySettings.gui(ZoomifySettings.kt:374)
	at dev.isxander.zoomify.Zoomify.tick(Zoomify.kt:130)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$deg000$fabric-lifecycle-events-v1$onEndTick(class_310.java:12980)

**Comment by Improvingtime50** [comment]
i have the same issue

**Comment by AngryAutist** [comment]
+1, hope this guy notices this and fixes it

**Comment by kyojinniko** [comment]
Actually the Mod Menu button and command crashes the game so you can't really change settings in this mod which really sucks...

**Comment by isXander** [comment]
Use YACL 1.x, not 2.x
