### ISSUE TITLE
[Quilt] Controlify constraint check fails for some reason

### ISSUE THREAD

**Issue by NyaomiDEV** [isXander/Zoomify#195]
It seems as though the constraint mechanism fails to detect the Controlify version on Quilt Loader.

```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'zoomify'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:56)
	at net.minecraft.class_310.<init>(class_310.java:487)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.IllegalStateException: Mod controlify is not constrained to version 2.x.x
	at dev.isxander.zoomify.integrations.IntegrationHelperKt.constrainModVersionIfLoaded(IntegrationHelper.kt:13)
	at dev.isxander.zoomify.Zoomify.onInitializeClient(Zoomify.kt:76)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$1(Hooks.java:56)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62)
	... 15 more
```

**Comment by isXander** [comment]
You need to use Controlify 2.x

**Comment by NyaomiDEV** [comment]
> You need to use Controlify 2.x

It's 2.0.0-beta3 for 1.20.4

**Comment by NyaomiDEV** [comment]
Retested with Controlify 2.0.0-beta5, constraint still fails.
