### ISSUE TITLE
[Fabric] Zoomify conflicts with Controlify mod in 1.20.6

### ISSUE THREAD

**Issue by Yeuogu** [isXander/Zoomify#201]
Zoomify (version zoomify-2.13.4+1.20.6) makes an error when Controlify mod (version Controlify-2.0.0-beta.10+1.20.6) when starting up the game.

`Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Controlify' (controlify) 2.0.0-beta.10+1.20.6 with any version that is compatible with:
		 - zoomify 2.13.4+1.20.6
More details:
	 - Mod 'Controlify' (controlify) 2.0.0-beta.10+1.20.6 is incompatible with version 2.13.4 or earlier of mod 'Zoomify' (zoomify), but a matching version is present: 2.13.4+1.20.6!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
`

**Comment by isXander** [comment]
Update to Zoomify 2.13.5
